### ISSUE TITLE
Add a description in the GitHub repository

### ISSUE THREAD

**Issue by zenorocha** [pubnub/pubnub-polymer#1]
http://customelements.io/?q=pubnub-polymer

**Comment by zenorocha** [comment]
:up:

**Comment by zenorocha** [comment]
:up:

**Comment by girliemac** [comment]
Oooo, I will! :+1:

**Comment by girliemac** [comment]
Hi Zeno,
does this automatically pull the desc from bower.json? I just re-registered to bower.

**Comment by zenorocha** [comment]
It actually pulls from GitHub:

![screen shot 2015-03-12 at 4 42 33 pm](https://cloud.githubusercontent.com/assets/398893/6626603/d1688448-c8d6-11e4-85bb-ec5b519c917e.png)

**Comment by girliemac** [comment]
Ahhhh, I see! I just added the desc & closing the issue!
Thank you :-)

**Comment by zenorocha** [comment]
;D
